apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: memoryleak-web-ingress  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /swagger    
spec:
  rules:
  - host: #{ingress}#   
    http:
      paths:
      - path: /
        backend:
          serviceName: memoryleak-web-service
          servicePort: 80
  tls:
  - hosts:
    -  #{ingress}#   